tag-name = "$VERSION"
news-file = "NEWS"
verify-command = "autoreconf -i && ./configure && make distcheck"
tarball-location = []
release-timeout = 5

[[update_version]]
path = "configure.ac"
new-line = "m4_define([SUBUNIT_MAJOR_VERSION], [$MAJOR_VERSION])"

[[update_version]]
path = "configure.ac"
new-line = "m4_define([SUBUNIT_MINOR_VERSION], [$MINOR_VERSION])"

[[update_version]]
path = "configure.ac"
new-line = "m4_define([SUBUNIT_MICRO_VERSION], [$MICRO_VERSION])"

[[update_version]]
path = "python/subunit/__init__.py"
new-line = "__version__ = $STATUS_TUPLED_VERSION"

[launchpad]
project = "subunit"
